apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shareify-Project/shareify-notification-service.git
    targetRevision: dev
    path: charts/notification-service
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: shareify-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
